// Table of contents shown on the home page.
// Page numbers are the ones printed in the book.
// A page that is not in the website yet is shown as "coming soon".
// zoom (optional) enlarges the drawing inside its circle, e.g. 1.5.

const CONTENTS = {
  chapters: [
    {
      title: 'Getting to know each other',
      pages: [2, 5],
      color: '#f05f4b',
      image: 'img/ms-fatigato.png',
    },
    {
      title: 'Classroom Bank',
      pages: [6, 17],
      color: '#8e2de2',
      image: 'img/bank-bird.png',
    },
    {
      title: 'Pronouns & To Be',
      pages: [18, 27],
      color: '#4aa8ec',
      image: 'img/tobe-p18.png',
    },
    {
      title: 'Present Simple',
      pages: [30, 37],
      color: '#c97df6',
      image: 'img/game-p34.png',
      zoom: 1.8,
    },
    {
      title: 'Home',
      pages: [38, 43],
      color: '#c9de3c',
      image: 'img/home/sofa.png',
    },
    {
      title: 'Describing people',
      pages: [44, 53],
      color: '#f96d5a',
      image: 'img/face-p40.png',
      zoom: 1.6,
    },
    {
      title: 'Literature: Metaphors',
      pages: [54, 63],
      color: '#7b3fc4',
      image: 'img/metaphors-p50.svg',
    },
    {
      title: 'Personality',
      pages: [64, 67],
      color: '#c08be8',
    },
    {
      title: 'Greek mythology',
      pages: [68, 77],
      color: '#fe7366',
      image: 'img/greekstatue-p49.jpg',
    },
  ],

  topics: [
    { title: 'Verb to be', color: '#7b3fc4', pages: [[2, 3], [18, 19], [22, 27]] },
    { title: 'Subject pronouns', color: '#4aa8ec', pages: [[18, 21]] },
    { title: 'Yes/no questions', color: '#f05f4b', pages: [[2, 3]] },
    { title: 'Money vocabulary', color: '#3aa04a', pages: [[6, 7]] },
    { title: 'Writing a weekly email', color: '#4a6cf0', pages: [[12, 13]] },
    { title: 'Test practice: pronouns & to be', color: '#e3b505', pages: [[24, 25]] },
    { title: 'Possessive adjectives', color: '#8e2de2', pages: [[26, 27], [70, 70]] },
    { title: 'Saxon genitive', color: '#4aa8ec', pages: [[28, 29], [36, 36]] },
    { title: 'Present simple', color: '#c97df6', pages: [[30, 33], [36, 37]] },
    { title: 'Adverbs of frequency', color: '#8e2de2', pages: [[31, 31]] },
    { title: 'Conversation game', color: '#fa6e5f', pages: [[34, 35]] },
    { title: 'Oral test: self-assessment', color: '#8e2de2', pages: [[37, 37]] },
    { title: 'Prepositions of place', color: '#3d9a3d', pages: [[38, 38], [42, 43]] },
    { title: 'Home vocabulary: spell & unlock', color: '#c9de3c', pages: [[40, 40]] },
    { title: 'Rooms of the house: decorate the house', color: '#4b924d', pages: [[41, 41]] },
    { title: 'Room missions (prepositions game)', color: '#3d9a3d', pages: [[43, 43]] },
    { title: 'Reading: Coraline', color: '#c9de3c', pages: [[38, 39]] },
    { title: 'Body description', color: '#f96d5a', pages: [[44, 45], [52, 53]] },
    { title: 'Personality: the Big 5', color: '#c08be8', pages: [[64, 65]] },
    { title: 'Personality adjectives', color: '#f96d5a', pages: [[66, 67]] },
    { title: 'Detective games: slash & draw', color: '#f96d5a', pages: [[46, 47]] },
    { title: 'Identikit: find the thief', color: '#c2384a', pages: [[48, 48]] },
    { title: 'Doctor Grammar & Word Lego', color: '#f9806e', pages: [[49, 49]] },
    { title: 'The Description Ladder', color: '#c08be8', pages: [[50, 51]] },
    { title: 'Greek gods', color: '#fe7366', pages: [[68, 68]] },
    { title: 'Reading: Prometheus', color: '#4aa8ec', pages: [[69, 69]] },
    { title: 'Reading: Persephone', color: '#fd7366', pages: [[70, 71]] },
    { title: 'Drama: Persephone, the play', color: '#fd7366', pages: [[72, 75]] },
    { title: 'Reading: Circe', color: '#f9a191', pages: [[76, 77]] },
    { title: 'Family vocabulary', color: '#fd7366', pages: [[76, 76]] },
    { title: 'Metaphors: what they are', color: '#7b3fc4', pages: [[54, 54]] },
    { title: 'Metaphors rule 1: not to be taken literally', color: '#f05f4b', pages: [[55, 56]] },
    { title: 'Idioms', color: '#f05f4b', pages: [[55, 55]] },
    { title: 'Metaphors rule 2: cannot be reversed', color: '#8e2de2', pages: [[57, 57]] },
    { title: 'Metaphors rule 3: the Stroop test game', color: '#4aa8ec', pages: [[58, 58]] },
    { title: 'Metaphors rule 4: metaphorical meaning (game)', color: '#3aa04a', pages: [[59, 60]] },
    { title: 'Simile vs metaphor', color: '#f08a5d', pages: [[61, 61]] },
    { title: 'Metaphor workshop & poem', color: '#c08be8', pages: [[62, 63]] },
    { title: 'Writing a book review', color: '#3d8f3d', pages: [[16, 17]] },
  ],
};
